# Generated by Django 5.2.5 on 2025-09-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_course_price_lesson_price"),
        ("users", "0003_subscription"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentCourseStripe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Дата оплаты"),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        help_text="Укажите сумму оплаты", verbose_name="Сумма оплаты"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату",
                        max_length=400,
                        null=True,
                        verbose_name="Ссылку на оплату",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=False, verbose_name="Статус оплаты"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите оплаченный курс",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments_stripe",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Выберите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments_stripe",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж Stripe",
                "verbose_name_plural": "Платежи Stripe",
            },
        ),
    ]
