# Generated by Django 5.2.5 on 2025-09-22 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_paymentcoursestripe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcoursestripe",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите сумму оплаты",
                verbose_name="Сумма оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="paymentcoursestripe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберите пользователя",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments_stripe",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
