# Generated by Django 5.2.5 on 2025-09-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_paymentcoursestripe_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcoursestripe",
            name="session_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите ID сессии",
                max_length=255,
                null=True,
                verbose_name="ID сессии",
            ),
        ),
    ]
