# Generated by Django 5.2.5 on 2025-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите стоимость курса",
                null=True,
                verbose_name="Стоимость курса",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Укажите стоимость курса",
                null=True,
                verbose_name="Стоимость курса",
            ),
        ),
    ]
